### PR TITLE
Added French locale

### PR DESCRIPTION
**Pull request by Gauvino**
I've added french translations and fix path syntax

Spoiler: thanks for all you're work it's really insane !

### CODE REVIEW

**Comment by endrl** [comment]
Thank you for your kind words and contribution! May i ask why did you moved the translations into another sub directory and what does it fix?

**Comment by Gauvino** [comment]
Just to have the project more organize ^^
Doesn't fix anything

**Comment by endrl** [comment]
Ah great. If you need a player you can checkout my jellfin-vue fork.

**Comment by endrl** [comment]
The stack is now available as docker compose file

**Pull request merged**
